
global:
  postgresql:
    auth:
      postgresPassword:  
      database: postgres
      username: 
app:
  config: 
    db_host: my-app-postgresql
    db_name: postgres
    db_port: 5432
  port: 3000
  image: tienpvse1/k8s-simple:4b9fd8f956cf27d1f9586d38f0b42fadc69a8165
  name: testing-app
  metadata:
    labels:
      app: testing-app

