
global:
  postgresql:
    auth:
      postgresPassword:  
      database: postgres
      username: 
app:
  config: 
    db_host: my-app-postgresql
    db_name: postgres
    db_port: 5432
  port: 3000
  image: tienpvse1/k8s-simple:fe23a153238875a00ed367e75babb1e8a8fa8e98
  name: testing-app
  metadata:
    labels:
      app: testing-app

