apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  db_host: {{ .Values.app.config.db_host }}
  db_port: {{ .Values.app.config.db_port | quote }}
  db_name: {{ .Values.app.config.db_name }}
