apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  db_password: {{ .Values.global.postgresql.auth.postgresPassword | b64enc }}
  db_username: {{ .Values.global.postgresql.auth.username | b64enc }}
